# Generated by Django 3.2.7 on 2021-10-03 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='events',
            field=models.ManyToManyField(to='api.Event'),
        ),
        migrations.CreateModel(
            name='SyncedProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_block_height', models.IntegerField()),
                ('syncing', models.BooleanField(default=False)),
                ('contract_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contractaddress')),
            ],
        ),
    ]
