# Generated by Django 3.2.7 on 2021-10-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211003_0625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='LogEvent',
        ),
    ]
