# Generated by Django 3.2.7 on 2021-10-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_event_logevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logevent',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=30),
        ),
    ]
